### ISSUE TITLE
Python 3 error?

### ISSUE THREAD

**Issue by albireox** [sdss/sdss_install#2]
Hi Ben,

I tried sdss_install with github and works great. I had a problem when trying to install a product with Python 3, though. When I run this using python 3.6.3 I got

```
[manga@manga:sdssdb]$ sdss_install -F -d -r /uufs/chpc.utah.edu/common/home/sdss09/software --github sdssdb 0.1.1
sdssinstall - INFO - Preparing to install in /uufs/chpc.utah.edu/common/home/sdss09/software/github/sdssdb/0.1.1 (overwriting due to force option)
sdssinstall - INFO - Running command: git clone https://github.com/sdss/sdssdb.git sdssdb-0.1.1
sdssinstall - INFO - Completed GitHub clone of repository sdssdb
sdssinstall - INFO - Running command: git checkout tags/0.1.1
sdssinstall - INFO - Completed checkout of tag 0.1.1 and removal of .git directory
sdssinstall - ERROR - Could not exec modules python shell. AttributeError("'_Environ' object has no attribute 'has_key'",)
sdssinstall - ERROR - Could not exec modules python shell. AttributeError("'_Environ' object has no attribute 'has_key'",)
sdssinstall - INFO - Installing in /uufs/chpc.utah.edu/common/home/sdss09/software/github/sdssdb/0.1.1
sdssinstall - INFO - Done! (failed modules)
```

It checked out the repo correctly but didn't create the module file. The same command using python 2.7 worked fine.

**Comment by nbmurphy** [comment]
For the TCL SDSS modules currently used at Utah, the python shell only works in Python 2.7.11 not Python 3x. So, this is not an issue with sdss_install itself. Instead, it's a TCL shell problem. Once Utah transitions to Lua modules this should not be an issue.

**Comment by joelbrownstein** [comment]
ironically, sdss_install will be the tool used to transition sdss software to [LUA modules at Utah](https://crowd.sdss.utah.edu/issues/?jql=project%20%3D%20CLUSTER%20AND%20component%20%3D%20%22LUA%20Modules%22), since we will need all new modulefiles
